name: Update EPG and YAML

on:
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch: 

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Install Dependencies
        run: go mod tidy  

      - name: Run Update Script
        run: go run main.go

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add epg.xml
          git diff --cached --quiet || (git commit -m "Auto-update EPG")
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}